x-sentry-service-config:
  version: 0.1
  service_name: postgres
  dependencies:
    postgres:
      description: "PostgreSQL is a powerful, open source object-relational database system"
  modes:
    default: [postgres]

services:
  postgres:
    image: ghcr.io/getsentry/image-mirror-library-postgres:18-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: sentry
    command:
      [
        postgres,
        -c,
        wal_level=logical,
        -c,
        max_replication_slots=1,
        -c,
        max_wal_senders=1,
      ]
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - devservices
    volumes:
      - postgres-data-v18:/var/lib/postgresql
    ports:
      - 127.0.0.1:5432:5432
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - orchestrator=devservices
    restart: unless-stopped

volumes:
  postgres-data-v18:


networks:
  devservices:
    name: devservices
    external: true
